### PR TITLE
Fix installing packages with blueprint

### PR DESCRIPTION
**Pull request by ksin**
@BrianSipple https://github.com/Ticketfly-UI/ticketfly-css/issues/24

### CODE REVIEW

**Comment by BrianSipple** [comment]
@ksin I'm still a bit confused by this. According to the Ember CLI API, there should be [no difference in the behavior/outcome of either argument style](https://ember-cli.com/api/classes/Blueprint.html#method_addPackagesToProject).

I think what we need to do is change `afterInstall` to `beforeInstall`, because the error of not finding `broccoli-postcss-single` is occurring when we try to transform CSS inside of `index.js`

**Comment by ksin** [comment]
Amended. Unsure how to test this. I tried `ember install` on this specific branch, but that doesn't run the blueprint.

**Comment by BrianSipple** [comment]
Ah, you have to run it manuall with `ember g ticketfly-css`.

**Comment by BrianSipple** [comment]
@ksin I agree, though -- testing this particular change seems tricky. I can run the addon in isolation, and run the blueprint in isolation, but how to run both together :thinking:? Even when linking in an external application, you'd have to manually run the blueprint first, in which case the dependencies will be there regardless when the addon runs.

Right now, though, I'm okay with trusting in determinism. Since `beforeInstall` runs before anything else in the addon itself, we should be able to have confidence in the way Ember CLI itself works 😄.

**Pull request merged**
